### ISSUE TITLE
Errors!

### ISSUE THREAD

**Issue by GM123456789** [Tee7even/Presents#2]
#### Issue description

When ever I opened the server for some while and someone opens the presents, it will show 2errors per seconds(avg)
#### Versions
- Presents version:1.0
- Nukkit version:#341
#### Crashdump or console output

```
Paste here
```

 [ALERT] java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:25)
    at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:50)
    at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:557)
    at cn.nukkit.Player.checkNearEntities(Player.java:1155)
    at cn.nukkit.Player.processMovement(Player.java:1319)
    at cn.nukkit.Player.onUpdate(Player.java:1423)
    at cn.nukkit.level.Level.doTick(Level.java:681)
    at cn.nukkit.Server.checkTickUpdates(Server.java:903)
    at cn.nukkit.Server.tick(Server.java:965)
    at cn.nukkit.Server.tickProcessor(Server.java:768)
    at cn.nukkit.Server.start(Server.java:748)
    at cn.nukkit.Server.<init>(Server.java:445)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.NullPointerException
    at net.tee7even.presents.Chest.itemEntityEquals(Chest.java:134)
    at net.tee7even.presents.Presents.isChestItemEntity(Presents.java:120)
    at net.tee7even.presents.EventListener.onItemPickup(EventListener.java:38)
    ... 17 more

**Comment by Tee7even** [comment]
I got it, will be fixed in a few minutes.

**Comment by karpovichv** [comment]
Fixed
