### ISSUE TITLE
Disabling Plugin in latest version

### ISSUE THREAD

**Issue by Adam1609** [Tee7even/Presents#3]
#### Issue description

Disabling plugin when updating the latest version
#### Versions
- Presents version: 1.2
- Nukkit version: #436
#### Crashdump or console output

```
2016-9-3 00:53:13 [INFO] Enabling Presents v1.2
2016-9-3 00:53:13 [ALERT] java.lang.NullPointerException
    at net.tee7even.presents.Chest.<init>(Chest.java:46)
    at net.tee7even.presents.provider.YamlProvider.loadChests(YamlProvider.java:36)
    at net.tee7even.presents.Presents.onEnable(Presents.java:67)
    at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
    at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)
    at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:456)
    at cn.nukkit.Server.enablePlugin(Server.java:618)
    at cn.nukkit.Server.enablePlugins(Server.java:607)
    at cn.nukkit.Server.<init>(Server.java:454)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-9-3 00:53:13 [INFO] Disabling Presents v1.2
2016-9-3 00:53:13 [ALERT] java.lang.NullPointerException
    at net.tee7even.presents.Presents.onDisable(Presents.java:81)
    at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91)
    at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:133)
    at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:528)
    at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:462)
    at cn.nukkit.Server.enablePlugin(Server.java:618)
    at cn.nukkit.Server.enablePlugins(Server.java:607)
    at cn.nukkit.Server.<init>(Server.java:454)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

**Comment by karpovichv** [comment]
It works perfectly fine on my local server with both latest Nukkit and Presents... And this exception seems pretty odd to me. Anyway, I can't guarantee that all Jenkins builds work right, so try [this one](http://ci.regularbox.com/job/Nukkit/).

**Comment by daniktheboss** [comment]
Please import to php thanks

**Comment by karpovichv** [comment]
I'm not going to rewrite this for php, thanks.

**Comment by daniktheboss** [comment]
OK, thanks

**Comment by Adam1609** [comment]
Latest version causes leashes (bug when opening chest, showing human entity
